name: Deploy to docker hub

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com

      - name: Build image
        if: success()
        run: docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/cli:${IMAGE_TAG} .

      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker/cli@master
        with:
          args: push docker.pkg.github.com/${GITHUB_REPOSITORY}/cli:${IMAGE_TAG}
